In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([2, 3, 4, 5])
for i in a1:
    for j in a2:
        if(i == j):
            print(j)

2
3
4


In [3]:
r = np.random.rand(3, 3, 3)*10
r

array([[[0.97590069, 7.69727321, 8.27528621],
        [7.12458993, 3.8499206 , 7.51729437],
        [2.20619984, 6.35977719, 4.68554384]],

       [[4.16033347, 4.25929965, 1.06911295],
        [6.64072642, 0.1655785 , 7.47226973],
        [3.96224093, 4.00800381, 7.11037737]],

       [[3.69363927, 7.87040459, 0.07965624],
        [7.73380733, 5.13059493, 4.73201677],
        [2.57530338, 6.19528774, 5.65881112]]])

In [4]:
r1 = np.random.rand(5, 5)*10
print(r1)
r1.sort()
rmax = np.array([r1[i, 4] for i in range(0, 5)])
rmin = np.array([r1[i, 0] for i in range(0, 5)])
rmax.sort()
rmin.sort()
print('Maximum element is', rmax[4], '\nMinimum element is', rmin[0])

[[8.42810705 7.06988806 7.32624588 1.87297875 4.89572798]
 [9.54874197 6.59698163 9.31994709 9.24964604 6.71270209]
 [5.86282923 3.57781134 7.54745598 9.26604363 8.43823303]
 [2.17791677 1.18857857 9.91792813 5.7520465  3.87451943]
 [0.74337554 7.0484933  9.60896821 4.66391014 0.78840442]]
Maximum element is 9.917928130454566 
Minimum element is 0.7433755434118561
